# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SL_B57uzqMmCo9p5THv8S0EGZOslu_eF
"""

import streamlit as st
import pandas as pd
from datetime import datetime

st.set_page_config(page_title="BüroImGrünen (BIG) - Verleihsystem", layout="wide")
st.title("🌿 BüroImGrünen (BIG) - Pflanzenverleih-Verwaltung")

if "kunden" not in st.session_state:
    st.session_state.kunden = []
if "auftraege" not in st.session_state:
    st.session_state.auftraege = []

PFLANZEN_BESTAND = ["Ficus Benjamina", "Monstera Deliciosa", "Goldfruchtpalme", "Bogenhanf", "Elefantenfuss"]
TOPF_FARBEN = ["pistaziengrün", "betongrau"]
TOPF_DURCHMESSER = ["24cm", "28cm"]

menu = st.sidebar.radio("Navigation", ["📄 Übersicht / Dashboard", "👤 Kunden & Events anlegen", "📦 Pflanzen zuteilen", "🚚 Transport & Rückgabe"])

st.sidebar.markdown("---")
st.sidebar.caption(f"⚡ Streamlit Version: {st.__version__}")
st.sidebar.caption(f"📊 Pandas Version: {pd.__version__}")

if menu == "📄 Übersicht / Dashboard":
    st.header("Aktuelle Verleihaufträge")
    if not st.session_state.auftraege:
        st.info("Noch keine Aufträge im System erfasst.")
    else:
        df = pd.DataFrame(st.session_state.auftraege)
        st.dataframe(df, use_container_width=True)

elif menu == "👤 Kunden & Events anlegen":
    st.header("1. Kundendaten & Event-Details erfassen")
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Kundendaten (Stammdaten)")
        kunden_name = st.text_input("Name des Kunden / Unternehmens")
        kunden_tel = st.text_input("Telefonnummer")
        kunden_email = st.text_input("E-Mail-Adresse")
        kunden_adresse = st.text_area("Rechnungsanschrift")

    with col2:
        st.subheader("Event-Details")
        event_name = st.text_input("Name der Veranstaltung")
        event_datum = st.date_input("Veranstaltungsdatum", min_value=datetime.today())
        event_adresse = st.text_area("Veranstaltungsort (Lieferadresse)")
        stockwerk = st.number_input("Stockwerk", min_value=0, step=1)
        aufzug = st.checkbox("Aufzug vorhanden?")
        ansprechpartner = st.text_input("Ansprechpartner vor Ort")

    if st.button("Kunde & Event保存", type="primary"):
        if kunden_name and event_name:
            neuer_kunde = {
                "id": len(st.session_state.kunden) + 1,
                "name": kunden_name,
                "telefon": kunden_tel,
                "email": kunden_email,
                "adresse": kunden_adresse,
                "event_name": event_name,
                "event_datum": str(event_datum),
                "event_adresse": event_adresse,
                "stockwerk": stockwerk,
                "aufzug": "Ja" if aufzug else "Nein",
                "ansprechpartner": ansprechpartner
            }
            st.session_state.kunden.append(neuer_kunde)
            st.success(f"Kunde '{kunden_name}' für Event '{event_name}' erfolgreich angelegt!")
        else:
            st.error("Bitte mindestens Kundenname und Eventname ausfüllen!")

elif menu == "📦 Pflanzen zuteilen":
    st.header("2. Pflanzen & Töpfe einem Auftrag zuweisen")

    if not st.session_state.kunden:
        st.warning("Bitte legen Sie zuerst unter 'Kunden & Events anlegen' einen Kunden an.")
    else:
        kunden_optionen = {f"{k['name']} - {k['event_name']}": k for k in st.session_state.kunden}
        auswahl = st.selectbox("Wähle den Kunden/Auftrag aus:", list(kunden_optionen.keys()))
        gewaehlter_kunde = kunden_optionen[auswahl]

        st.info("Maximale Anzahl: 10 Pflanzen pro Event erlaubt.")
        pflanzen_anzahl = st.slider("Anzahl der zu leihenden Pflanzen:", min_value=1, max_value=10, value=3)

        gewaehlte_pflanzen = []
        st.subheader("Konfiguration der Pflanzen")

        for i in range(pflanzen_anzahl):
            c1, c2, c3 = st.columns(3)
            with c1:
                p_typ = st.selectbox(f"Pflanze #{i+1} Typ", PFLANZEN_BESTAND, key=f"p_{i}")
            with c2:
                t_farbe = st.selectbox(f"Topffarbe #{i+1}", TOPF_FARBEN, key=f"f_{i}")
            with c3:
                t_dm = st.selectbox(f"Durchmesser #{i+1}", TOPF_DURCHMESSER, key=f"d_{i}")
            gewaehlte_pflanzen.append({"typ": p_typ, "farbe": t_farbe, "durchmesser": t_dm})

        if st.button("Pflanzenauswahl für Auftrag bestätigen", type="primary"):
            neuer_auftrag = {
                "Auftrags-ID": len(st.session_state.auftraege) + 1,
                "Kunde": gewaehlter_kunde["name"],
                "Event": gewaehlter_kunde["event_name"],
                "Datum": gewaehlter_kunde["event_datum"],
                "Anzahl Pflanzen": pflanzen_anzahl,
                "Details Pflanzen": str(gewaehlte_pflanzen),
                "Transport durch": "Wird im nächsten Schritt geplant",
                "Status": "Pflanzen zugewiesen",
                "Zustand Rückgabe": "Offen"
            }
            st.session_state.auftraege.append(neuer_auftrag)
            st.success("Pflanzen erfolgreich für den Auftrag reserviert!")

elif menu == "🚚 Transport & Rückgabe":
    st.header("3. Logistik & Qualitätskontrolle")

    if not st.session_state.auftraege:
        st.warning("Keine aktiven Aufträge mit zugewiesenen Pflanzen vorhanden.")
    else:
        auftrags_ids = [a["Auftrags-ID"] for a in st.session_state.auftraege]
        gewaehlte_id = st.selectbox("Wähle die Auftrags-ID zur Bearbeitung:", auftrags_ids)

        for idx, auftrag in enumerate(st.session_state.auftraege):
            if auftrag["Auftrags-ID"] == gewaehlte_id:
                st.write(f"**Kunde:** {auftrag['Kunde']} | **Event:** {auftrag['Event']}")
                transport = st.radio("Wer übernimmt den Transport (Bringen/Abholen)?", ["BIG (Martin & Tonja)", "Kunde (Selbstabholer)"])
                zustand = st.radio("Zustand der Pflanzen bei der Rückgabe:", ["Unbeschädigt (Kaution voll zurück)", "Beschädigt (Kautionsanspruch prüfen)"])

                if st.button("Logistik- und Status-Update speichern"):
                    st.session_state.auftraege[idx]["Transport durch"] = transport
                    st.session_state.auftraege[idx]["Zustand Rückgabe"] = zustand
                    st.session_state.auftraege[idx]["Status"] = "Abgeschlossen" if zustand == "Unbeschädigt (Kaution voll zurück)" else "Prüfung Kautionsanspruch"
                    st.success("Auftragsstatus aktualisiert! Siehe Übersicht Dashboard.")
                    break